config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'

  put 'admin/update/:user_id' => "admin#update"
  patch 'admin/update/:user_id' => "admin#update"

  put 'admin/remove_admin/:user_id' => "admin#remove_admin"
  patch 'admin/remove_admin/:user_id' => "admin#remove_admin"

  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "omniauth_callbacks"}

  resources :owners
  resources :apartments do
   get 'map_location'        # Add this and the "do" "end"
  end

   root 'apartments#index'

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  belongs_to :user
  geocoded_by :full_address
  after_validation :geocode
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :user, presence: true
  validates :address_1, :city, :state, :postal_code, length: {minimum: 2}
  resourcify

  def full_address
    @full_address = address_1 + " " + address_2 + " " + city + " " + state + " " + postal_code.to_s + " " + country
  end


end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource
  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all

    @pindrop = Gmaps4rails.build_markers(@apartments) do |apartment, marker|
      marker.lat apartment.latitude
      marker.lng apartment.longitude
      marker.infowindow apartment.full_address
    end

  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
    @apartments = Apartment.find(params[:id]) #@apartments may also be found using the set_apartment method provided by scaffolding

   @pindrop = Gmaps4rails.build_markers(@apartments) do |apartment, marker|
     marker.lat apartment.latitude
     marker.lng apartment.longitude
     marker.infowindow apartment.full_address
   end

  end

  # GET /apartments/new
  def new
    @apartment = current_user.apartments.build

  end

  # GET /apartments/1/edit
  def edit
    if @apartment.user == current_user
      true
    else
      redirect_to '/'
    end
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = current_user.apartments.build(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    if @apartment.user == current_user
      @apartment.destroy
      respond_to do |format|
        format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to '/'
    end
  end

  # add in the map location method to call on it in the js file : render the json object
  def map_location
    @apartments = Apartment.find(params[:apartment_id])
    @hash = Gmaps4rails.build_markers(@apartments) do |apartment, marker|
      marker.lat apartment.latitude
      marker.lng apartment.longitude
      marker.infowindow apartment.full_address
    end
    render json: @hash.to_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:address_1, :address_2, :city, :postal_code, :state, :country, :user_id, :lattitude, :longitude, :image)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_form.html.erb
<% if @apartment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

    <ul>
    <% @apartment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @apartment, html: { multipart: true} do |f| %>
  <%= f.file_field :image %>

  <div class="field">
    <%= f.label :address_1 %><br>
    <%= f.text_field :address_1 %>
  </div>
  <div class="field">
    <%= f.label :address_2 %><br>
    <%= f.text_field :address_2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.number_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form' %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<h1>Listing Apartments</h1>

<table class="table">
  <thead>
    <tr>
      <th>Address 1</th>
      <th>Address 2</th>
      <th>City</th>
      <th>Postal code</th>
      <th>State</th>
      <th>Country</th>
      <th>User</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.address_1 %></td>
        <td><%= apartment.address_2 %></td>
        <td><%= apartment.city %></td>
        <td><%= apartment.state %></td>
        <td><%= apartment.postal_code %></td>
        <td><%= apartment.country %></td>
        <td><%= apartment.user.email %></td>

        <% if !apartment.image_file_name.nil? %>
          <td><%= image_tag apartment.image.url(:small)%></td>
        <% else%>
          <td></td>
        <%end%>
        <td><%= link_to 'Show', apartment %></td>
        <% if !current_user.nil? %>
          <% if apartment.user == current_user || current_user.has_role?(:admin) %>
            <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
            <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%end%>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Apartment', new_apartment_path %>
<br>
<hr>

<div id="index_map">Google map will appear here...</div>
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({
    provider: {},
    internal: {id: 'index_map'}
  },
  function() {
    markers = handler.addMarkers(<%=raw @pindrop.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(10);
  }
);
</script>

<br>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form' %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

 <%= link_to image_tag(@apartment.image.url(:large)), @apartment.image.url %>

<p>
  <strong>Address 1:</strong>
  <%= @apartment.address_1 %>
</p>

<p>
  <strong>Address 2:</strong>
  <%= @apartment.address_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @apartment.city %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @apartment.postal_code %>
</p>

<p>
  <strong>State:</strong>
  <%= @apartment.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @apartment.country %>
</p>

<p>
  <strong>Lattitude:</strong>
  <%= @apartment.latitude%>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @apartment.longitude%>
</p>

<p>
  <strong>Owner:</strong>
<%= @apartment.user.email%></a>
</p>

<hr>
<div id="map" data-apartment-id="<%=@apartment.id%>">Google map will appear here...</div>

<br>
<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>